### Импорт библиотеки NumPy с общепринятым сокращением

In [ ]:
import numpy as np

### Примеры создания массивов

In [4]:
arr_from_list = np.array([1, 2, 3, 4])
print("Массив из списка: ", arr_from_list)

Массив из списка:  [1 2 3 4]


### Создание массивов с помощью встроенных функций

In [7]:
zeros_arr = np.zeros(5)          # массив из нулей
ones_arr = np.ones((2, 3))       # двумерный массив из единиц
range_arr = np.arange(0, 10, 2)  # массив как range(), но через Numpy

print("Нули:", zeros_arr)
print("Единицы (2x3):\n", ones_arr)
print("arange(0, 10, 2):", range_arr)

Нули: [0. 0. 0. 0. 0.]
Единицы (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
arange(0, 10, 2): [0 2 4 6 8]


### Демонстрация атрибутов shape и dtype

In [8]:
sample_array = np.array([[1.0, 2.0], [3.0, 4.0]])
print("Массив:\n", sample_array)
print("Форма (shape):", sample_array.shape)
print("Тип данных (dtype):", sample_array.dtype)

Массив:
 [[1. 2.]
 [3. 4.]]
Форма (shape): (2, 2)
Тип данных (dtype): float64


### Примеры индексирования и срезов

In [9]:
# Индексирование и срезы
a = np.array([10, 20, 30, 40, 50])

# Получение отдельного элемента
element = a[2]  # третий элемент (индексация с 0)
print("Элемент по индексу 2:", element)

# Извлечение подмассива с помощью среза
subarray = a[1:4]  # элементы с индексами 1, 2, 3
print("Срез [1:4]:", subarray)

# Пример с двумерным массивом
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Подмассив b[0:2, 1:3]:\n", b[0:2, 1:3])

Элемент по индексу 2: 30
Срез [1:4]: [20 30 40]
Подмассив b[0:2, 1:3]:
 [[2 3]
 [5 6]]


### Примеры векторных операций и базовых статистик

In [11]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Поэлементное сложение и умножение
sum_xy = x + y
multi_xy = x * y

print("x + y =", sum_xy)
print("x * y =", multi_xy)

# Статистика: среднее значение
mean_x = x.mean()
print("Среднее значение x:", mean_x)

# Пример с двумерным массивом
matrix = np.array([[1, 2], [3, 4]])
print("Среднее по всему массиву: ", matrix.mean())
print("Сумма по столбцам: ", matrix.sum(axis=0))

x + y = [5 7 9]
x * y = [ 4 10 18]
Среднее значение x: 2.0
Среднее по всему массиву:  2.5
Сумма по столбцам:  [4 6]
